#+HUGO_BASE_DIR: ./
#+HUGO_SECTION: post
#+author: ざしきわらし

* その他ページ群
** ざしきわらしの駄文置き場
   :PROPERTIES:
   :EXPORT_HUGO_SECTION: /
   :EXPORT_FILE_NAME: _index
   :END:
   ざしきわらしの駄文置き場です。
   適当に書き散らかしたものをおいていきます。
   恋愛物のお題は主に [[http://have-a.chew.jp/][確かに恋だった]] からもらってきています。

* Novels
** DONE 確かに恋だった                                  :恋愛:確かに恋だった:
   CLOSED: [2019-05-16 Thu 05:32]
   :PROPERTIES:
   :EXPORT_FILE_NAME: tashikani_koi_datta
   :END:

   それは確かに恋だった。
   今となってはもうどうにもできないことだが、あの頃は恋がどんなものかなんてわかっちゃいなかった。
   結果、あの恋は実るどころか自覚すらままならないままに終わりを迎えてしまった。
   大事なものは失って初めて気づくとよく言うが、まさにそうだった。

   別れを迎えて初めて気づく恋心、もう会えなくなってから気づく大切な人。
   自覚して行動した上での終わりならまだよかったのだろうか。
   それとも、木っ端微塵に砕け散ることなく終わりを迎えたのは幸運だったのだろうか。
   砕け散らない可能性があったのかなんて、今となっては確かめるすべもない。
   
   ああ、もう一度やり直せるなら、次は別れなど吹き飛ばすほどの情熱でもって特攻をかけるのに。
   ああ、現実は非情だ。こんなにも熱い思いをどこへやればいいというのか。

   あれは確かに恋だった。
   あの頃抱えていた純粋な恋心は、もう今の僕にはないものだ。
   今の僕にあるのは打算にまみれた恋と呼べるかも怪しい感情ばかりだ。
   それでも、僕はそれを恋と呼ぶ。それもまた確かに恋なのだと。
   
# Local Variables:
# eval: (org-hugo-auto-export-mode)
# End:
