#+HUGO_BASE_DIR: ./
#+HUGO_SECTION: post
#+author: ざしきわらし

* その他ページ群
** ざしきわらしの駄文置き場
   :PROPERTIES:
   :EXPORT_HUGO_SECTION: /
   :EXPORT_FILE_NAME: _index
   :END:
   ざしきわらしの駄文置き場です。
   適当に書き散らかしたものをおいていきます。
   恋愛物のお題は主に [[http://have-a.chew.jp/][確かに恋だった]] からもらってきています。

* Novels
** DONE 確かに恋だった                                  :恋愛:確かに恋だった:
   CLOSED: [2019-05-16 Thu 05:32]
   :PROPERTIES:
   :EXPORT_FILE_NAME: tashikani_koi_datta
   :END:

   それは確かに恋だった。
   今となってはもうどうにもできないことだが、あの頃は恋がどんなものかなんてわかっちゃいなかった。
   結果、あの恋は実るどころか自覚すらままならないままに終わりを迎えてしまった。
   大事なものは失って初めて気づくとよく言うが、まさにそうだった。

   別れを迎えて初めて気づく恋心、もう会えなくなってから気づく大切な人。
   自覚して行動した上での終わりならまだよかったのだろうか。
   それとも、木っ端微塵に砕け散ることなく終わりを迎えたのは幸運だったのだろうか。
   砕け散らない可能性があったのかなんて、今となっては確かめるすべもない。

   ああ、もう一度やり直せるなら、次は別れなど吹き飛ばすほどの情熱でもって特攻をかけるのに。
   ああ、現実は非情だ。こんなにも熱い思いをどこへやればいいというのか。

   あれは確かに恋だった。
   あの頃抱えていた純粋な恋心は、もう今の僕にはないものだ。
   今の僕にあるのは打算にまみれた恋と呼べるかも怪しい感情ばかりだ。
   それでも、僕はそれを恋と呼ぶ。それもまた確かに恋なのだと。

** DONE なんて不毛な、それでも恋                        :恋愛:確かに恋だった:
   CLOSED: [2019-05-16 Thu 06:02]
   :PROPERTIES:
   :EXPORT_FILE_NAME: nante_fumouna_soredemo_koi
   :END:
   私はあの人に恋をしている。でも、あの人は私の方が私の方を見てくれることはない。
   あの人のお気に入りは私よりもずっとかわいい。私なんかじゃ勝ち目がない。
   それでも私はあの人に恋をしている。これが不毛な恋だと知りながらも。

   不毛なのがわかっているんだからやめられればいいんだけれど、そんなことできっこない。
   あの人に恋している私の心は、まるで私の物ではないかのように私のいうことを聞かなくなってしまった。
   自分のことなのに、自分ではどうにもできない。どうにかできるとしたらあの人だけ。
   でも、あの人が私の方をみてくれることはない。あの人にはもうお気に入りがいるのだから。

   あの人のお気に入りを恨むということはない。恨んだってどうにもならないのだから。
   でも、うらやましいという気持ちだけは止まらない。あの人にあんなに目を向けてもらえるなんて。
   私があの立場だったらと考えた回数は100をくだらない。それでも、現実はそうじゃない。
   うらやんだって、妄想したって、現実は変わらない。現実を変えるためには何か行動を起こさないといけない。
   それでも、私には何をどうすればこの現実を変えられるのかがわからない。

   ああ、この現実を変えるには何をどうしたらいいの。この不毛な恋をやめるにはどうしたらいいの。
   不毛だからと考えたって、心が勝手に恋をする。まるで言うことを聞かない私の心よ。
   どうしたら諦めてくれるの、どうやってもあの人は振り向いてはくれないのだから。
   ああ、自分の心さえどうにもできないのに、他人の心なんてどうにかできるわけがない。
   この不毛な恋にどうか終止符をください。

* Local Variables
# Local Variables:
# eval: (org-hugo-auto-export-mode)
# End:
